replaced Start/Stop Buttons with Switches
amosproj/amos2022ws03-software-oscilloscope pull request #123
Opened 2022-12-06 20:24 UTC by rabbit-zero

2022-12-06 20:59 UTC, leandertolksdorf requested changes
The toggle buttons are not working as intended on my machine (see video).

2022-12-06 20:59 UTC, leandertolksdorf commented on Apps/frontend/src/views/StartStopButton.svelte
> +	let switchLabelOn = "Started " + channel_id;
Not sure if the label "Started/Stopped" is needed anymore, as the toggle buttons already show the current state.

2022-12-06 20:59 UTC, leandertolksdorf commented on Apps/frontend/src/views/Oscilloscope.svelte
>            {#each { length: NUM_CHANNELS } as _, index}
When merging, please make sure to keep updating the indicators' start/stop state in the on:startStop function.

2022-12-06 20:59 UTC, leandertolksdorf commented
https://user-images.githubusercontent.com/55246283/206021669-e15120fb-0e65-4ad2-a7b6-5425b58cf9eb.mov

2022-12-06 21:13 UTC, PhlppKrmr requested changes
If you need something to orient yourself on look at #79, I think you can adopt quite a lot from it.

2022-12-06 21:13 UTC, PhlppKrmr commented on Apps/frontend/src/views/StartStopButton.svelte
> +off={switchLabelOff} design="slider" on:click={handleStartStop} />
What is `design="slider"` supposed to do?

2022-12-06 21:13 UTC, PhlppKrmr commented on Apps/frontend/src/views/StartStopButton.svelte
> +<Switch bind:value={hasStarted} hideLabel on={switchLabelOn}
You can look at what I did in #79 and change the color(s) of the the switch, maybe we can eben remove the label?

2022-12-07 09:28 UTC, PhlppKrmr approved these changes
Rest looks good.

2022-12-07 09:28 UTC, PhlppKrmr commented on Apps/frontend/src/views/Oscilloscope.svelte
> +        <div class="switches">
We don't have this class. Change to `sliders`

2022-12-07 10:03 UTC, jenswaechtler approved these changes

2022-12-07 11:17 UTC, jandegen approved these changes

2022-12-07 11:17 UTC, PhlppKrmr approved these changes

2022-12-07 11:18 UTC, merged