Feature/#106 refactoring front end sliders
amosproj/amos2022ws03-software-oscilloscope pull request #139
Opened 2022-12-14 08:40 UTC by jenswaechtler

Moves Slider in seperate file

2022-12-18 14:49 UTC, nicolaskolbenschlag requested changes
Implementation looks good but I think tests need to be adapted.

2022-12-20 14:57 UTC, nicolaskolbenschlag approved these changes

2022-12-20 21:43 UTC, motschel123 approved these changes

2022-12-20 21:45 UTC, motschel123 commented
I will bypass branch protection and prevent outdating again, because it has been approved before being outdated, and the merge from dev doesn't relate to this feature.

2022-12-20 21:45 UTC, merged