Feature/#127 gnd
amosproj/amos2022ws03-software-oscilloscope pull request #145
Opened 2022-12-14 18:58 UTC by nicolaskolbenschlag

Does anybody know why the line is not visible if the value us zero?

2022-12-20 12:01 UTC, jandegen requested changes

2022-12-20 12:01 UTC, jandegen commented on Apps/frontend/src/views/Oscilloscope.svelte
> +    if (isGND) {samples.fill(0.0);}
Maybe use a different array. Not sure about the performance when filling the huge array with zeros.
```javascript
if (isGND) {
    var gndSample = new Array(10).fill(0.0)
    waveElement.updateBuffer(gndSample, 0, 10)
    return
}
```

This way don't waste compute time with filling the array.

2022-12-21 10:27 UTC, PhlppKrmr requested changes

2022-12-21 10:27 UTC, PhlppKrmr commented on Apps/frontend/src/views/Oscilloscope.svelte
> +        <GNDButton
Think you need to lint this file again

2022-12-21 10:27 UTC, PhlppKrmr commented on Apps/frontend/src/components/GNDButton.svelte
> +    dispatch("gnd", { down: down });
Please use a more speaking event name, something like "setGround".

2023-01-11 09:36 UTC, closed without merging