Feature/#93 front end tests
amosproj/amos2022ws03-software-oscilloscope pull request #203
Opened 2023-01-30 15:26 UTC by leandertolksdorf

Current test coverage:

![Bildschirm­foto 2023-01-30 um 16 25 59](https://user-images.githubusercontent.com/55246283/215519347-ed721d8f-ec49-4983-bfdc-368b2e31ca8b.png)

I added more tests for frontend-only stuff like tooltips, but I'm really struggling with tests that involve signals from the backend. See file `cypress/e2e/2-indicators/line-indicators.cy.js`: I tried mocking the websocket connection to send a test sample array. And the message is received at the frontend. Problems are:

- The message data is received as a string like `1, 0, 0, ...` instead of an array buffer.
- Despite turning on the oscillator by clicking the start button, $osciEnabled is still false and the onmessage handler doesn't get to updating the other components.

2023-01-31 14:01 UTC, PhlppKrmr requested changes
Thanks for adding all those new tests :)

2023-01-31 21:17 UTC, leandertolksdorf commented on Apps/frontend/cypress/e2e/2-indicators/line-indicators.cy.js
> +  it("updates min value", () => {
That's what i pointed out in the pr description. Unfortunately after many hours, I coudn't figure out how to fix it so I'm leaving it out for now.

2023-01-31 21:20 UTC, leandertolksdorf commented on Apps/frontend/src/components/GNDButton.svelte
> +<Tooltip target={button} placement="bottom" data-cy="gnd-button-tooltip">{TOOLTIP_BUTTON_GND}</Tooltip>
How does it reformat? Doesn't do anything for me.

2023-01-31 21:25 UTC, leandertolksdorf commented on Apps/frontend/cypress/e2e/3-control-panel-top/gnd-button.cy.js
> +  // Stub is not working in the e2e test, createEventDispatcher still
As I didn't find a solution to this, I removed it just now and for next sprint we could consider using unit tests for such logic.

2023-01-31 21:26 UTC, leandertolksdorf commented on Apps/frontend/cypress/e2e/3-control-panel-top/general-buttons.cy.js
> +    cy.get('[data-cy="on-off-button"]').click();
Not sure what you meant, but to test if the reset button resets the on off button, I have to first toggle the on off button, right?

2023-01-31 21:29 UTC, leandertolksdorf commented on Apps/frontend/cypress/e2e/3-control-panel-top/reset-button.cy.js
> +
I added blank lines manually for now.

2023-01-31 23:34 UTC, motschel123 approved these changes
All tests running green, LGTM

2023-02-01 08:51 UTC, PhlppKrmr commented on Apps/frontend/src/components/GNDButton.svelte
> +<Tooltip target={button} placement="bottom" data-cy="gnd-button-tooltip">{TOOLTIP_BUTTON_GND}</Tooltip>
It reformats to multiline, but nothing major.

2023-02-01 08:58 UTC, PhlppKrmr approved these changes

2023-02-01 08:58 UTC, PhlppKrmr commented on Apps/frontend/cypress/e2e/2-control-panel/preset-config.cy.js
> +    cy.get('[data-cy="settings-button"]').click();
As far as I can tell the interim step of checking if the panel is/was open is missing.
`cy.get('[data-cy="preset-config-open-popup"]').should("be.visible");`

2023-02-01 08:58 UTC, PhlppKrmr commented on Apps/frontend/cypress/e2e/3-control-panel-top/general-buttons.cy.js
> +    cy.get('[data-cy="on-off-button"]').click();
Yeah, I just meant functionality-wise you would not actually need the extra step. When considering the label of the test it is even expected that you also click the button. My misunderstaning

2023-02-01 09:01 UTC, merged