updated vision and mission
amosproj/amos2022ws03-software-oscilloscope pull request #213
Opened 2023-02-01 10:56 UTC by jandegen

2023-02-03 10:27 UTC, jenswaechtler approved these changes
Wow, the slides look fantastic! Great job!

2023-02-03 10:43 UTC, nicolaskolbenschlag approved these changes

2023-02-04 15:06 UTC, motschel123 approved these changes

2023-02-05 10:08 UTC, nicolaskolbenschlag approved these changes

2023-02-05 19:02 UTC, PhlppKrmr approved these changes

2023-02-05 19:24 UTC, PhlppKrmr approved these changes

2023-02-06 09:47 UTC, leandertolksdorf approved these changes

2023-02-06 12:30 UTC, PhlppKrmr requested changes
Guess this is the place to mention the Bill of Materials. We still mention webgl-plot in there, should be removed.

2023-02-07 13:11 UTC, rabbit-zero approved these changes

2023-02-07 14:29 UTC, jenswaechtler approved these changes

2023-02-08 08:19 UTC, PhlppKrmr approved these changes

2023-02-08 08:19 UTC, PhlppKrmr approved these changes

2023-02-08 08:23 UTC, merged