Updated Build & Deployment Doci
amosproj/amos2022ws03-software-oscilloscope pull request #219
Opened 2023-02-05 11:22 UTC by jandegen

Checkout: [Build & Deployment Documentation](https://github.com/amosproj/amos2022ws03-software-oscilloscope/wiki/Build-&-Deployment-Documentation)

2023-02-05 11:56 UTC, nicolaskolbenschlag approved these changes

2023-02-05 19:00 UTC, PhlppKrmr approved these changes

2023-02-06 09:51 UTC, leandertolksdorf approved these changes

2023-02-06 10:08 UTC, jenswaechtler requested changes
I might be being overly picky here, but would it be possible for the submission to be (also) in PDF format?

2023-02-06 12:21 UTC, PhlppKrmr commented
> I might be being overly picky here, but would it be possible for the submission to be (also) in PDF format?

+1

2023-02-06 17:41 UTC, leandertolksdorf commented
> I might be being overly picky here, but would it be possible for the submission to be (also) in PDF format?

@jandegen in case you want the pdf to match the user docs, I used `npx md-to-pdf input.md` for converting.

2023-02-06 19:04 UTC, motschel123 approved these changes

2023-02-07 12:41 UTC, jenswaechtler approved these changes

2023-02-07 13:10 UTC, rabbit-zero approved these changes

2023-02-07 13:13 UTC, merged