Feature/#41 signal sine wave
amosproj/amos2022ws03-software-oscilloscope pull request #54
Opened 2022-11-12 08:24 UTC by nicolaskolbenschlag

2022-11-13 18:03 UTC, motschel123 requested changes
Running in _Apps/backend_ with `docker compose up --build` => panic because no receiving service was running. Maybe just catch an return with normal error message. 

Because of _docker_compose.yml_: `restart: always` it keeps restarting and panicking forever!!  
> Maybe restart: unless-stopped would be a better fit than restart: always. (Personal note) #50 


Running in _Apps_ with `docker compose up --build` => Sending and receiving is working. But I only get 0's being sent/received

2022-11-13 18:47 UTC, nicolaskolbenschlag commented
Okay, thank you for the review! So does it work with the correct docker configuration? The reason for the sending zeros is probably that the channels were not parameterized. SIG_FREQ_i can be used to adopt the frequency for the i th channel. Further there are SIG_AMP_i and SIG_TYP_i for signal amplitude and type.

2022-11-14 16:29 UTC, jandegen approved these changes

2022-11-15 16:16 UTC, rabbit-zero approved these changes

2022-11-15 17:20 UTC, leandertolksdorf commented on Apps/backend/src/main.rs
>  use std::{env};
Take care when merging.
The rust "backend" has been renamed to "generator" and the middleware node server has been moved out of frontend into "backend".

2022-11-15 19:15 UTC, merged