Feature/#31 data signal visualization from the node server
amosproj/amos2022ws03-software-oscilloscope pull request #57
Opened 2022-11-14 22:31 UTC by PhlppKrmr

Worked on this issue with @jandegen & @motschel123

2022-11-15 08:31 UTC, motschel123 approved these changes
LGTM

2022-11-15 13:31 UTC, rabbit-zero commented
looks fine

2022-11-15 13:32 UTC, rabbit-zero approved these changes

2022-11-15 15:29 UTC, jenswaechtler requested changes

2022-11-15 15:29 UTC, jenswaechtler commented on Apps/generator/src/main.rs
> +        socket.send(&bytes);
Unused result

2022-11-15 15:29 UTC, jenswaechtler commented on Apps/backend/package.json
> +  "type": "module",
I find it very difficult to do a review when there are a lot of linter improvements in between. This should actually be in the scope of an extra pull request.

2022-11-15 21:38 UTC, leon-juenemann commented
Build upon this a bit and created a new PR as I didn't want to clutter this up. It changes quite a lot.
https://github.com/amosproj/amos2022ws03-software-oscilloscope/pull/58

2022-11-16 09:38 UTC, jandegen approved these changes

2022-11-16 10:24 UTC, merged