Feature/#31 data signal visualization from the node server v1.0
amosproj/amos2022ws03-software-oscilloscope pull request #58
Opened 2022-11-15 21:35 UTC by leon-juenemann

![plot_signals](https://user-images.githubusercontent.com/32913978/202030090-c1cc72c2-71d9-4d05-93b1-da1987392f6c.png)

2022-11-15 21:37 UTC, leon-juenemann commented
I build upon this a bit and created a new branch. It changes quite a bit and I didn't want to crash this PR ;)

https://github.com/amosproj/amos2022ws03-software-oscilloscope/pull/58

2022-11-16 06:46 UTC, nicolaskolbenschlag approved these changes
With this implementation the signals for each channel are fixed and can not be parameterized via environment variables anymore. But as this was no requirement, it is fine for me.

2022-11-16 07:59 UTC, leandertolksdorf commented on Apps/backend/src/main.js
> +  port: 9000,
Maybe it's better to have the WebSocket use ENV vars for host and port like the UDP socket.

2022-11-16 08:01 UTC, leandertolksdorf commented on Apps/backend/src/main.js
>  server.on("message", (msg, rinfo) => {
Unused var rinfo

2022-11-16 08:10 UTC, leandertolksdorf commented on Apps/frontend/src/views/Oscilloscope.svelte
> +    socket = new WebSocket("ws://localhost:9000");
When using ws://backend:9000, it uses docker's internal network and you don't need to expose port 9000 on the backend.

2022-11-16 08:11 UTC, leandertolksdorf commented on Apps/frontend/src/views/SineWave.svelte
> +    x++;
In this case x = (x+1) % CANVAS_WIDTH would be more readable imo.

2022-11-16 08:14 UTC, leandertolksdorf requested changes
Some minor remarks at the JS part, cannot contribute much in Rust.

2022-11-16 08:17 UTC, leandertolksdorf commented
The plotting looks weird on my machine...

https://user-images.githubusercontent.com/55246283/202125467-953c2607-684e-4956-88e9-5756a90dd663.mov

2022-11-16 10:24 UTC, merged