btn #26 functionality
amosproj/amos2022ws03-software-oscilloscope pull request #66
Opened 2022-11-18 07:29 UTC by nicolaskolbenschlag

Signed-off-by: nicolaskolbenschlag <nicolas.kolbenschlag@googlemail.com>

2022-11-18 08:39 UTC, leandertolksdorf commented on Apps/frontend/src/views/Oscilloscope.svelte
> +      if (!isEnabled) { return; }
braces aren't needed here but that's a style preference.

2022-11-18 08:41 UTC, leandertolksdorf commented on Apps/frontend/src/views/Oscilloscope.svelte
> +    <OnOffButton on:switch-plot-enabled={(e) => {isEnabled = e.detail.enabled;}} />
I'd prefer the OnOffButton outside of the div.wrapper to 1. prevent weird any absolute positioning bugs
2. have the controls separated from the representation

2022-11-18 08:45 UTC, leandertolksdorf commented
wrote some comments and while you're on it, could you maybe rename SineWave.svelte to something more general, e.g. Wave or Plot?

2022-11-18 08:46 UTC, leandertolksdorf requested changes
.

2022-11-18 08:50 UTC, leandertolksdorf commented
Tests are missing.

2022-11-20 20:35 UTC, motschel123 commented
I am not sure about this in combination with the new #69 , what button are we using?

2022-11-21 19:48 UTC, nicolaskolbenschlag commented
Probably we will delete this PR as the tickets #26 and #28 are duplicates.

2022-11-22 16:27 UTC, merged