add StartStopButton
amosproj/amos2022ws03-software-oscilloscope pull request #69
Opened 2022-11-20 12:19 UTC by rabbit-zero

created button for start and stop plotting the signal 

closes #28

2022-11-20 19:00 UTC, leandertolksdorf commented on Apps/frontend/src/App.svelte
> +  import StartStopButton from "./views/StartStopButton.svelte";
unused import

2022-11-20 19:01 UTC, leandertolksdorf commented on Apps/frontend/src/views/SineWave.svelte
> +<StartStopButton on:startStop={async (event)=> {hasStarted = event.detail.buttonValue}} />
The component should be placed in the Oscilloscope.svelte component in my opinion.

2022-11-20 19:03 UTC, leandertolksdorf requested changes
Sorry if I missed something, but this does the same as #66, except that in #66 the drawing resumes at the point it stopped, right?

2022-11-20 20:34 UTC, motschel123 commented
I'm not certain about the requirements, but in my opinion we should discard all received stream data and start from the beginning (cleaning the old curves) as we click resume

2022-11-21 21:07 UTC, jenswaechtler requested changes
The button changes size when I click on it. Perhaps it depends on the text field. Not necessary scope of this issue, but perhaps you know a fix.

2022-11-22 14:08 UTC, rabbit-zero commented on Apps/frontend/src/views/Oscilloscope.svelte
> +
oh, I forgot to delete that

2022-11-22 15:54 UTC, jenswaechtler approved these changes
Looks good to me.

2022-11-22 17:14 UTC, PhlppKrmr commented
Just to clarify:
What @rabbit-zero implemented is perfectly fine, only the naming of the issue is a little onfortunate (start and freeze would've most likely been clearer).
We also asked Mr. Eckert on Monday whether he wants the feature @motschel123 mentions (clear canvas and restart). This is really low prio cause we can simply refresh the page itself, we don't need a button for that.

2022-11-22 17:20 UTC, PhlppKrmr approved these changes

2022-11-22 17:20 UTC, PhlppKrmr commented on Apps/frontend/src/views/StartStopButton.svelte
> +<button class="button-style button-up" on:click={handleStartStop}>
Funtionality works fine, only the styling could be improved (as @jenswaechtler already mentioned the text forces a different button size)
-> For me personally a simple button with the icons would be enough (as long as the size stays the same then)

2022-11-28 16:01 UTC, jenswaechtler commented
The pull request is against the main branch. This should be changed to dev.

2022-11-28 17:31 UTC, motschel123 reviewed
Should be into dev, as mentioned.
In my opinion Text/button size changes are not a problem for now.
Otherwise LGTM.

2022-11-30 08:29 UTC, leon-juenemann reviewed
I just changed the target to dev. CI/CD should pass now.

2022-11-30 11:20 UTC, jandegen approved these changes

2022-11-30 11:22 UTC, jenswaechtler approved these changes

2022-11-30 11:22 UTC, merged